title: James Yorston
logo: "https://avatars0.githubusercontent.com/u/7592585?s=400&u=5ed9d98361201f2822c90b8a9826324ea399223b&v=4"
description: > 
  10 years in technology most recently as Director of Engineering, VC at Carta
  <br><br>
  I've got a background in a number of sectors including FinTech, E-Commerce and Academic Research.
  <br><br>


  
theme: jekyll-theme-minimal
google_analytics: G-C5RDJ7E2FE
