title: James Yorston
logo: "https://avatars0.githubusercontent.com/u/7592585?s=400&u=5ed9d98361201f2822c90b8a9826324ea399223b&v=4"
description: > 
  9 years in technology most recently as CTO of Zero Gravity.
  <br><br>
  I've got a background in a number of sectors including FinTech, E-Commerce and Academic Research.
  <br><br>
  <a href="https://www.linkedin.com/in/jyorston">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-91188220-1 # your Google Analytics tracking ID here
