title: James Yorston
logo: "https://avatars0.githubusercontent.com/u/7592585?s=400&u=5ed9d98361201f2822c90b8a9826324ea399223b&v=4"
description: > 
  6+ years in Software Engineering most recently leading the technical team @toshi.co.
  <br><br>
  I've got a background in a number of sectors including FinTech, E-Commerce and academic research.
  <br><br>
  <a href="https://www.linkedin.com/in/jyorston">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-91188220-1 # your Google Analytics tracking ID here
